{{- $ci_path := printf "/%s" ((default "/" .Values.global.ci_path) | trim | trimAll "/") -}}
{{- $globals := ternary .Values.global.prod .Values.global.dev (eq .Values.global.env_name "prod") -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- if ne .Values.global.mon_probe "" }}
    synergy.ru/blackbox.probe: {{ .Values.global.mon_probe }}
    {{- end }}
    {{- if ne .Values.global.mon_code "" }}
    synergy.ru/blackbox.code: {{ .Values.global.mon_code }}
    {{- end }}
    {{- if ne .Values.global.www_redirect "no" }}
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    {{- end }}
    {{- if eq .Values.global.env_name "dev" }}
    nginx.ingress.kubernetes.io/auth-url: "http://dev-auth.auth.svc.cluster.local"
    {{- end }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      # Additional configuration snippet

      {{- if and (ne .Values.global.ci_path "") (ne .Values.global.ci_path "/") }}
      #rewrite ^([^.]*[^/])$ $1/ permanent;
      rewrite (?i)/{{ .Values.global.ci_path | trimAll "/" }}(/|$)(.*) /$2 break;
      {{- end }}
  name: ingress
spec:
  ingressClassName: "nginx"
  rules:
      - host: {{ .Values.global.ci_url }}
        http:
          paths:
          - backend:
              service:
                name: {{ .Values.global.appName }}
                port:
                  name: http
            pathType: Prefix
            {{- if and (ne .Values.global.ci_path "") (ne .Values.global.ci_path "/") }}
            path: /{{ .Values.global.ci_path | trimAll "/" }}
            {{- else }}
            path: /
            {{- end }}
---
{{- if eq .Values.global.env_name "prod" }}
{{- range $index, $mirror := .Values.mirrors }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      # Additional configuration snippet
      {{- if ne (default "" $.Values.block_code) "" }}
      {{- range $index, $country := $.Values.block_countries }}
      if ($geoip2_city_country_code = {{ $country.code }}) {
        return {{ $.Values.block_code }};
      }
      {{- end }}
      {{- end }}

      #rewrite ^([^.]*[^/])$ $1/ permanent;

      if ($is_args = '?') {
          rewrite {{ $mirror.path | trimSuffix "/" }}(/|$)(.*)   {{ if $mirror.subdir }}{{ $mirror.subdir }}{{ end }}/$2?$args{{- if $mirror.query }}&{{ $mirror.query }}{{- end }}? break;
      }

      if ($is_args = '') {
          rewrite {{ $mirror.path | trimSuffix "/" }}(/|$)(.*)   {{ if $mirror.subdir }}{{ $mirror.subdir }}{{ end }}/$2{{- if $mirror.query }}?{{ $mirror.query }}{{- end }} break;
      }

  name: mirror-{{ printf "%s%s" $mirror.host $mirror.path | replace "/" "-" | replace "_" "-" | trimSuffix "-" }}
spec:
  ingressClassName: "nginx"
  rules:
      - host: {{ $mirror.host }}
        http:
          paths:
            {{- if ne $mirror.path "/" }}
          - path: /{{ $mirror.path | trimAll "/" }}
            {{- else }}
          - path: /
            {{- end }}
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.global.appName }}
                port:
                  name: http
---
{{- range $index, $redirect := $mirror.redirect }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      # Additional configuration snippet
      add_header Cache-Control "private, max-age=0, no-cache";

      if ($is_args = '?') {
          rewrite {{ $redirect.path | trimSuffix "/" }}(/|$)(.*) https://{{ $mirror.host }}{{ $mirror.path | trimSuffix "/" }}/$2?$args? permanent;
      }

      if ($is_args = '') {
          rewrite {{ $redirect.path | trimSuffix "/" }}(/|$)(.*) https://{{ $mirror.host }}{{ $mirror.path | trimSuffix "/" }}/$2 permanent;
      }

  name: redirect-m-{{ printf "%s%s" $redirect.host $redirect.path | replace "/" "-" | replace "_" "-" | trimSuffix "-" }}
spec:
  ingressClassName: "nginx"
  rules:
      - host: {{ $redirect.host }}
        http:
          paths:
            {{- if ne $redirect.path "/" }}
          - path: /{{ $redirect.path | trimAll "/" }}
            {{- else }}
          - path: /
            {{- end }}
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.global.appName }}
                port:
                  name: http
---
{{- end }}

{{- end }}
{{- end }}

{{- if eq .Values.global.env_name "prod" }}
{{- range .Values.redirects }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      # Additional configuration snippet
      add_header Cache-Control "private, max-age=0, no-cache";

      if ($is_args = '?') {
          rewrite {{ .path | trimSuffix "/" }}(/|$)(.*) https://{{ $.Values.global.ci_url }}{{- if ne $ci_path "/" }}{{ $ci_path }}{{- end}}/$2?$args{{- if .query }}&{{ .query }}{{- end }}? permanent;
      }

      if ($is_args = '') {
          rewrite {{ .path | trimSuffix "/" }}(/|$)(.*) https://{{ $.Values.global.ci_url }}{{- if ne $ci_path "/" }}{{ $ci_path }}{{- end}}/$2{{- if .query }}?{{ .query }}{{- end }} permanent;
      }

  name: redirect-{{ printf "%s%s" .host .path | replace "/" "-" | replace "_" "-" | trimSuffix "-" }}
spec:
  ingressClassName: "nginx"
  rules:
      - host: {{ .host }}
        http:
          paths:
            {{- if ne .path "/" }}
          - path: /{{ .path | trimAll "/" }}
            {{- else }}
          - path: /
            {{- end }}
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.global.appName }}
                port:
                  name: http
---
{{- end }}
{{- end }}
